spring:
  config:
    activate:
      on-profile: prod

server:
  port: 80

logging:
  level:
    com.example.demo: WARN
    org.springframework: WARN

app:
  name: "To-Do List Manager [PROD]"
  version: "1.0.0"
  dev-mode: false
  debug-enabled: false